theme = "catppuccin"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
mouse = false
completion-replace = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal]
"ret" = "goto_word"
